imu_topic: "/boxi/livox/imu"
lidar_topic: "/boxi/hesai/points"

sensors:
  imu:
    acc_cov: 0.1
    gyr_cov: 0.1
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001

  lidar:
    min_range: 0.25
    range_cov: 0.02
    angle_cov: 0.1

  # [quat : w, x, y, z] — Livox IMU -> Hesai LiDAR (from extrinsics_tf_static.txt)
  t_exts: [-0.007343, -0.018607, 0.13838]
  q_exts: [0.001224, 0.705142, -0.709063, 0.001557]

downsample:
  resolution: 1.0

max_iter: 4

voxel_map:
  resolution: 1.0
  max_layer: 2
  layer_size: [5, 5, 5, 5, 5]
  max_point_size: 1000
  plane_threshold: 0.05

  map_sliding_en: true
  sliding_thresh: 8.0
  half_map_size: 150
