imu_topic: "/os_cloud_node/imu"
lidar_topic: "/os_cloud_node/points"

sensors:
  imu:
    acc_cov: 0.1
    gyr_cov: 0.1
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001

  lidar:
    min_range: 0.25
    range_cov: 0.02
    angle_cov: 0.15

    #Multi-cam
    t_exts: [-0.011, -0.02329, 0.04412]
    q_exts: [ 1.0, 0.0, 0.0, 0.0]

    #Stereo-Cam
    # t_exts: [-0.006253, 0.011775, 0.028535]
    # q_exts: [0.0, 0.0, 0.0, 1.0]

downsample:
  resolution: 0.5

max_iter: 4

voxel_map:
  resolution: 1.0
  max_layer: 2
  layer_size: [5, 5, 5, 5, 5]
  max_point_size: 1000
  plane_threshold: 0.01